let dados = [
    {
        nome: "Ancilostomíase",
        outros: "Amarelão",
        agentes: "Ancylostoma duodenale, Necator americanus",
        tipoAgente: "Helminto (nematódeo)",
        descricao: "Infecção intestinal causada por nematódeos que se alimentam do sangue do hospedeiro. Diagnóstico por exame parasitológico de fezes. Possíveis complicações incluem anemia grave e desnutrição. Notificação compulsória: (NÃO)",
        periodoIncubacao: "4 - 8 semanas",
        transmissao: "Penetração ativa das larvas através da pele, geralmente nos pés",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo contaminado com fezes",
        sintomas: "Coceira no local de penetração, anemia, dor abdominal, diarreia, fadiga",
        tratamento: "Vermífugos (albendazol, mebendazol)",
        prevencao: "Uso de calçados, saneamento básico, tratamento de água, educação em saúde",
        gruposRisco: "Trabalhadores rurais, crianças em áreas endêmicas",
        distribuicaoGeografica: "Prevalente em regiões tropicais e subtropicais, especialmente em áreas com saneamento precário",
        sazonalidade: "Maior incidência em épocas chuvosas",
        resistencia: "Não há relatos significativos de resistência aos medicamentos"
    },
    {
        nome: "Antraz",
        outros: "Carbúnculo",
        agentes: "Bacillus anthracis",
        tipoAgente: "Bacilo gram-positivo formador de esporos",
        descricao: "Doença infecciosa zoonótica que pode acometer a pele, o trato respiratório ou o trato gastrointestinal. O diagnóstico pode ser feito por cultura, PCR e imunofluorescência. Possíveis complicações incluem septicemia, choque e morte. Notificação compulsória: (SIM)",
        periodoIncubacao: "1 - 7 dias",
        transmissao: "Contato com animais infectados, esporos presentes no solo, inalação de esporos",
        definitivo: "Ruminantes, humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo contaminado com esporos",
        sintomas: "Cutânea: úlcera com crosta negra, febre, mal-estar, respiratória: febre, tosse, dificuldade respiratória, gastrointestinal: náuseas, vômitos, diarreia",
        tratamento: "Antibióticos (ciprofloxacina, doxiciclina), antitoxina",
        prevencao: "Vacinação de animais e pessoas em risco, medidas de biossegurança, descontaminação de produtos animais",
        gruposRisco: "Trabalhadores que lidam com animais ou produtos animais, militares",
        distribuicaoGeografica: "Ocorre em todo o mundo, mais comum em áreas agrícolas",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Geralmente sensível aos antibióticos recomendados"
    },
    {
        nome: "Ascaridíase",
        outros: "Lombriga",
        agentes: "Ascaris lumbricoides",
        tipoAgente: "Helminto (nematódeo)",
        descricao: "Doença parasitária intestinal causada por um verme cilíndrico. Diagnóstico por exame parasitológico de fezes. Possíveis complicações incluem obstrução intestinal, perfuração intestinal e migração do verme para outros órgãos. Notificação compulsória: (NÃO)",
        periodoIncubacao: "60 - 75 dias",
        transmissao: "Ingestão de ovos do parasita presentes em alimentos, água ou solo contaminados com fezes humanas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Dor abdominal, náuseas, vômitos, diarreia, perda de peso, tosse, febre",
        tratamento: "Vermífugos (mebendazol, albendazol, ivermectina)",
        prevencao: "Saneamento básico, higiene pessoal, lavagem de alimentos, uso de calçados, educação em saúde",
        gruposRisco: "Crianças em áreas com saneamento precário",
        distribuicaoGeografica: "Mundial, mais prevalente em regiões tropicais e subtropicais com saneamento inadequado",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Baixa resistência aos medicamentos utilizados"
    },
    {
        nome: "Blastomicose",
        outros: "Doença de Gilchrist",
        agentes: "Blastomyces dermatitidis",
        tipoAgente: "Fungo dimórfico",
        descricao: "Infecção fúngica pulmonar crônica que pode se disseminar para outros órgãos. Diagnóstico por cultura, exame microscópico e sorologia. Possíveis complicações incluem insuficiência respiratória e disseminação para o sistema nervoso central. Notificação compulsória: (NÃO)",
        periodoIncubacao: "3 - 15 semanas",
        transmissao: "Inalação de esporos do fungo",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo, material em decomposição",
        sintomas: "Febre, tosse, fadiga, lesões cutâneas, dor no peito, perda de peso",
        tratamento: "Antifúngicos (itraconazol, anfotericina B)",
        prevencao: "Evitar áreas com alta incidência do fungo, usar máscaras em áreas contaminadas",
        gruposRisco: "Trabalhadores florestais, caçadores, pessoas com sistema imunológico comprometido",
        distribuicaoGeografica: "Endêmica na América do Norte, especialmente nos vales dos rios Mississippi e Ohio",
        sazonalidade: "Maior incidência no outono e inverno",
        resistencia: "Geralmente sensível aos antifúngicos recomendados"
    },
    {
        nome: "Botulismo",
        outros: "Intoxicação botulínica",
        agentes: "Clostridium botulinum",
        tipoAgente: "Bacilo gram-positivo formador de esporos",
        descricao: "Doença neurotóxica grave causada pela ingestão de alimentos contaminados pela neurotoxina botulínica. Diagnóstico clínico e laboratorial (detecção da toxina). Possíveis complicações incluem paralisia respiratória e morte. Notificação compulsória: (SIM)",
        periodoIncubacao: "12 - 36 horas",
        transmissao: "Ingestão de alimentos contaminados, contaminação de feridas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo, água, alimentos",
        sintomas: "Visão dupla, dificuldade para engolir, fraqueza muscular, paralisia, boca seca",
        tratamento: "Soro antibotulínico, suporte respiratório",
        prevencao: "Conservação adequada de alimentos, cozimento adequado, não consumir alimentos enlatados estufados, higiene na preparação de alimentos",
        gruposRisco: "Consumidores de conservas caseiras, usuários de drogas injetáveis",
        distribuicaoGeografica: "Ocorre mundialmente, mais comum em regiões com práticas inadequadas de conservação de alimentos",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Não aplicável (doença causada por toxina)"
    },
    {
        nome: "Candidíase",
        outros: "Sapinho e monilíase",
        agentes: "Candida albicans, outras espécies de Candida",
        tipoAgente: "Fungo (levedura)",
        descricao: "Infecção fúngica que pode afetar a pele, boca, vagina e outros órgãos. Diagnóstico por exame microscópico direto e cultura. Possíveis complicações incluem infecções sistêmicas em pacientes imunocomprometidos. Notificação compulsória: (NÃO)",
        periodoIncubacao: "2 - 5 dias",
        transmissao: "Contato direto com a levedura, objetos contaminados, transmissão vertical",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Flora normal do corpo humano",
        sintomas: "Vermelhidão, coceira, placas brancas na boca ou vagina, ardência, corrimento vaginal",
        tratamento: "Antifúngicos tópicos ou sistêmicos (fluconazol, nistatina)",
        prevencao: "Manutenção da higiene, tratamento de doenças crônicas, evitar uso excessivo de antibióticos",
        gruposRisco: "Recém-nascidos, idosos, diabéticos, pessoas com HIV/AIDS",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Algumas cepas podem desenvolver resistência a antifúngicos comuns"
    },
    {
        nome: "Catapora",
        outros: "Varicela",
        agentes: "Vírus varicela-zoster (VZV)",
        tipoAgente: "Vírus DNA envelopado",
        descricao: "Doença infecciosa altamente contagiosa caracterizada por erupção cutânea com vesículas pruriginosas. Diagnóstico geralmente clínico, confirmado por testes laboratoriais se necessário. Algumas possíveis complicações incluem infecções bacterianas secundárias, pneumonia e encefalite. Notificação compulsória: (SIM)",
        periodoIncubacao: "10 - 21 dias",
        transmissao: "Contato direto com as lesões, gotículas respiratórias e contato com objetos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Febre, mal-estar, perda de apetite, erupção cutânea com vesículas pruriginosas",
        tratamento: "Antivirais (em casos graves), cuidados para aliviar os sintomas",
        prevencao: "Vacina contra a varicela, isolamento do doente",
        gruposRisco: "Crianças, gestantes não imunes, pessoas com sistema imunológico comprometido",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Mais comum no final do inverno e início da primavera em climas temperados",
        resistencia: "Geralmente sensível aos antivirais recomendados"
    },
    {
        nome: "Chicungunha",
        outros: "Chikungunya",
        agentes: "Vírus Chikungunya",
        tipoAgente: "Vírus RNA envelopado",
        descricao: "Doença viral transmitida por mosquitos, caracterizada por febre alta, dores articulares intensas e erupção cutânea. Diagnóstico por testes sorológicos e PCR. Possíveis complicações incluem artrites crônicas e encefalite. Notificação compulsória: (SIM)",
        periodoIncubacao: "3 - 7 dias",
        transmissao: "Picada do mosquito Aedes aegypti ou Aedes albopictus infectado",
        definitivo: "Humanos",
        intermediario: "Aedes aegypti, Aedes albopictus",
        reservatorio: "Humanos, primatas não humanos",
        sintomas: "Febre alta, dores articulares intensas, dor de cabeça, fadiga, erupção cutânea, náuseas",
        tratamento: "Tratamento sintomático (analgésicos, anti-inflamatórios)",
        prevencao: "Combate ao mosquito Aedes, uso de repelentes, proteção contra picadas",
        gruposRisco: "Idosos, recém-nascidos, pessoas com doenças crônicas",
        distribuicaoGeografica: "África, Ásia, América do Sul e Central, Caribe",
        sazonalidade: "Maior incidência em épocas chuvosas",
        resistencia: "Não aplicável (doença viral)"
    },
    {
        nome: "Cisticercose",
        outros: "Neurocisticercose",
        agentes: "Taenia solium (forma larval)",
        tipoAgente: "Helminto (cestoda)",
        descricao: "Doença parasitária causada pela ingestão de ovos de Taenia solium, que se desenvolvem em larvas (cisticercos) em diversos órgãos do corpo humano. Diagnóstico por exames de imagem, sorologia e biópsia. Possíveis complicações incluem convulsões, hipertensão intracraniana e hidrocefalia. Notificação compulsória: (SIM)",
        periodoIncubacao: "Semanas a anos",
        transmissao: "Ingestão de alimentos ou água contaminados com ovos de T. solium",
        definitivo: "Humanos (para a forma adulta da T. solium)",
        intermediario: "Humanos (para a forma larval)",
        reservatorio: "Humanos",
        sintomas: "Sintomas variam de acordo com o local da infecção, mas podem incluir dores de cabeça, convulsões, alterações visuais, confusão mental",
        tratamento: "Tratamento cirúrgico e medicamentos antiparasitários (albendazol, praziquantel)",
        prevencao: "Higiene das mãos, saneamento básico, tratamento adequado da teníase, cozimento adequado da carne suína",
        gruposRisco: "Pessoas que vivem em áreas com saneamento precário",
        distribuicaoGeografica: "Prevalente em países em desenvolvimento, especialmente na América Latina, África e Ásia",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Geralmente sensível aos antiparasitários recomendados"
    },
    {
        nome: "Cólera",
        outros: "Cólera epidêmica",
        agentes: "Vibrio cholerae",
        tipoAgente: "Bactéria gram-negativa",
        descricao: "Doença infecciosa aguda do intestino delgado, causada pela ingestão de água ou alimentos contaminados. Diagnóstico por cultura de fezes e testes rápidos. Possíveis complicações incluem desidratação grave, choque hipovolêmico e insuficiência renal. Notificação compulsória: (SIM)",
        periodoIncubacao: "2 horas a 5 dias",
        transmissao: "Fecal-oral, através de água ou alimentos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Água e alimentos contaminados, fezes humanas",
        sintomas: "Diarreia aquosa intensa, vômitos, desidratação rápida, cãibras musculares",
        tratamento: "Reposição de líquidos e eletrólitos, antibióticos (em casos graves)",
        prevencao: "Saneamento básico, higiene pessoal, tratamento de água e alimentos, vacinação em áreas endêmicas",
        gruposRisco: "Pessoas vivendo em áreas com saneamento precário, viajantes para áreas endêmicas",
        distribuicaoGeografica: "Endêmica em partes da África, Ásia e América Latina",
        sazonalidade: "Maior incidência em estações chuvosas em áreas endêmicas",
        resistencia: "Algumas cepas têm desenvolvido resistência a antibióticos comuns"
    },
    {
        nome: "Coqueluche",
        outros: "Tosse comprida",
        agentes: "Bordetella pertussis",
        tipoAgente: "Bactéria gram-negativa",
        descricao: "Doença infecciosa aguda das vias aéreas superiores, caracterizada por tosse paroxística intensa. O diagnóstico pode ser feito por cultura, PCR e teste rápido. Possíveis complicações incluem pneumonia, convulsões e encefalopatia. Notificação compulsória: (SIM)",
        periodoIncubacao: "7 - 10 dias",
        transmissao: "Gotículas respiratórias",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Tosse intensa e prolongada, vômitos após acessos de tosse, dificuldade para respirar, cianose",
        tratamento: "Antibióticos (eritromicina, azitromicina), tratamento sintomático",
        prevencao: "Vacina tríplice bacteriana (DTP), reforços, isolamento do doente",
        gruposRisco: "Bebês e crianças pequenas não vacinadas, idosos",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Maior incidência no verão e outono",
        resistencia: "Algumas cepas têm mostrado resistência a macrolídeos"
    },
    {
        nome: "COVID-19",
        outros: "Doença por coronavírus 2019",
        agentes: "SARS-CoV-2",
        tipoAgente: "Vírus RNA envelopado",
        descricao: "Doença infecciosa causada por um coronavírus, com sintomas que podem variar de leves a graves, incluindo febre, tosse, fadiga e dificuldade para respirar. Diagnóstico por RT-PCR, testes rápidos de antígeno. Possíveis complicações incluem pneumonia grave, síndrome respiratória aguda grave e trombose. Notificação compulsória: (SIM)",
        periodoIncubacao: "2 - 14 dias",
        transmissao: "Gotículas respiratórias, aerossóis, contato com superfícies contaminadas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Possivelmente morcegos, ainda sob investigação",
        sintomas: "Febre, tosse, fadiga, perda de olfato e paladar, dificuldade para respirar, dores musculares",
        tratamento: "Tratamento dos sintomas, antivirais, suporte respiratório em casos graves",
        prevencao: "Vacinação, uso de máscara, higiene das mãos, distanciamento social",
        gruposRisco: "Idosos, pessoas com comorbidades (hipertensão, diabetes, doenças cardíacas)",
        distribuicaoGeografica: "Pandêmica, afetando todos os continentes",
        sazonalidade: "Padrões sazonais ainda em estudo",
        resistencia: "Surgimento de variantes com potencial de escape imunológico"
    },
    {
        nome: "Dengue",
        outros: "Febre quebra-ossos",
        agentes: "Vírus da dengue (DENV-1, DENV-2, DENV-3, DENV-4)",
        tipoAgente: "Vírus RNA",
        descricao: "Doença infecciosa transmitida por mosquitos, caracterizada por febre alta, dores no corpo, dor de cabeça e erupção cutânea. Diagnóstico por testes sorológicos e PCR. Possíveis complicações incluem dengue grave com choque e hemorragias. Notificação compulsória: (SIM)",
        periodoIncubacao: "3 - 14 dias",
        transmissao: "Picada do mosquito Aedes aegypti infectado",
        definitivo: "Humanos",
        intermediario: "Mosquito Aedes aegypti",
        reservatorio: "Humanos, possivelmente primatas em ciclo silvestre",
        sintomas: "Febre alta, dor de cabeça, dores musculares e articulares, erupção cutânea, náuseas, vômitos",
        tratamento: "Sintomático (repouso, hidratação), monitoramento para sinais de agravamento",
        prevencao: "Combate ao mosquito transmissor, uso de repelentes, telas em janelas",
        gruposRisco: "Crianças, idosos, gestantes, pessoas com doenças crônicas",
        distribuicaoGeografica: "Regiões tropicais e subtropicais da Ásia, África e Américas",
        sazonalidade: "Maior incidência em épocas quentes e chuvosas",
        resistencia: "Não aplicável (doença viral)"
    },
    {
        nome: "Doença de Chagas",
        outros: "Tripanossomíase americana",
        agentes: "Trypanosoma cruzi",
        tipoAgente: "Protozoário flagelado",
        descricao: "Doença parasitária crônica que acomete o sistema nervoso autônomo, o trato gastrointestinal e o coração. O diagnóstico pode ser feito por exame parasitológico, xenodiagnóstico e sorologia. Possíveis complicações incluem insuficiência cardíaca e dilatação de órgãos. Notificação compulsória: (SIM)",
        periodoIncubacao: "5 - 14 dias para fase aguda, anos para fase crônica",
        transmissao: "Picada de triatomíneos (barbeiros), transfusão sanguínea, transplante de órgãos, congênita, oral",
        definitivo: "Humanos, mamíferos silvestres e domésticos",
        intermediario: "Triatomíneos",
        reservatorio: "Mamíferos silvestres, humanos",
        sintomas: "Fase aguda: febre, edema, linfadenopatia; fase crônica: cardiomegalia, megaesôfago, megacólon",
        tratamento: "Benznidazol e nifurtimox (fase aguda), tratamento sintomático (fase crônica)",
        prevencao: "Controle de vetores, triagem de sangue, educação em saúde",
        gruposRisco: "Pessoas vivendo em áreas rurais com presença do vetor",
        distribuicaoGeografica: "América Latina, com casos em outros continentes devido à migração",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Algumas cepas têm mostrado resistência aos medicamentos disponíveis"
    },
    {
        nome: "Erisipela",
        outros: "Celulite estreptocócica",
        agentes: "Streptococcus pyogenes",
        tipoAgente: "Bactéria gram-positiva",
        descricao: "Infecção bacteriana aguda da pele, caracterizada por vermelhidão, inchaço e dor, com possíveis complicações como celulite, linfangite e bacteremia. Diagnóstico principalmente clínico, às vezes confirmado por cultura. Notificação compulsória: (NÃO)",
        periodoIncubacao: "1 - 7 dias",
        transmissao: "Penetração do Streptococcus pyogenes por feridas na pele",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Vermelhidão, inchaço, dor, febre, calafrios, mal-estar",
        tratamento: "Antibióticos (penicilina, eritromicina em alérgicos à penicilina)",
        prevencao: "Cuidado com feridas, higiene pessoal, tratamento de infecções de pele",
        gruposRisco: "Idosos, diabéticos, pessoas com sistema imunológico comprometido",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Mais comum em climas quentes e úmidos",
        resistencia: "Geralmente sensível à penicilina, mas algumas cepas podem ser resistentes a outros antibióticos"
    },
    {
        nome: "Esquistossomose",
        outros: "Barriga d'água",
        agentes: "Schistosoma mansoni, Schistosoma haematobium, Schistosoma japonicum",
        tipoAgente: "Helminto (trematódeo)",
        descricao: "Doença parasitária causada por vermes platelmintos, que afetam principalmente o fígado e os intestinos. Diagnóstico por exame parasitológico de fezes ou urina, e testes sorológicos. Possíveis complicações incluem fibrose hepática, hipertensão portal e câncer de bexiga. Notificação compulsória: (SIM)",
        periodoIncubacao: "2 - 6 semanas",
        transmissao: "Penetração ativa das larvas cercárias através da pele, durante o contato com água doce contaminada",
        definitivo: "Humanos",
        intermediario: "Caramujos aquáticos",
        reservatorio: "Humanos",
        sintomas: "Coceira no local de penetração, febre, dor abdominal, diarreia, hepatomegalia, esplenomegalia",
        tratamento: "Medicamentos antiparasitários (praziquantel)",
        prevencao: "Saneamento básico, educação em saúde, controle de caramujos, evitar contato com águas contaminadas",
        gruposRisco: "Pessoas que têm contato frequente com águas contaminadas",
        distribuicaoGeografica: "África, Oriente Médio, Caribe, América do Sul, Sudeste Asiático",
        sazonalidade: "Maior transmissão em épocas chuvosas",
        resistencia: "Não há relatos significativos de resistência ao praziquantel"
    },
    {
        nome: "Forúnculo",
        outros: "Furúnculo",
        agentes: "Staphylococcus aureus",
        tipoAgente: "Bactéria gram-positiva",
        descricao: "Infecção aguda da raiz do pelo, caracterizada por um nódulo vermelho e doloroso. Diagnóstico geralmente clínico. Possíveis complicações incluem celulite e abscesso. Notificação compulsória: (NÃO)",
        periodoIncubacao: "1 - 5 dias",
        transmissao: "Contato com a pele infectada, auto-inoculação",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Nódulo vermelho e doloroso, pus, dor local, febre em casos mais graves",
        tratamento: "Antibióticos (em casos graves), drenagem do abscesso, cuidados locais",
        prevencao: "Higiene pessoal, cuidado com feridas, evitar compartilhar objetos pessoais",
        gruposRisco: "Diabéticos, pessoas com sistema imunológico comprometido",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Mais comum em climas quentes e úmidos",
        resistencia: "Algumas cepas de S. aureus são resistentes à meticilina (MRSA)"
    },
    {
        nome: "Giardíase",
        outros: "Lambliase",
        agentes: "Giardia lamblia (também conhecida como G. intestinalis ou G. duodenalis)",
        tipoAgente: "Protozoário flagelado",
        descricao: "Doença infecciosa causada por um protozoário, afetando principalmente o intestino delgado. Diagnóstico por exame parasitológico de fezes. Possíveis complicações incluem má absorção e desnutrição. Notificação compulsória: (NÃO)",
        periodoIncubacao: "1 - 3 semanas",
        transmissao: "Fecal-oral, através de água ou alimentos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos, cães domésticos e outros animais",
        sintomas: "Diarreia, dores abdominais, flatulência, perda de peso, náuseas",
        tratamento: "Medicamentos antiparasitários (metronidazol, tinidazol)",
        prevencao: "Higiene pessoal, tratamento de água e alimentos, saneamento básico",
        gruposRisco: "Crianças em creches, viajantes para áreas endêmicas",
        distribuicaoGeografica: "Mundial, mais comum em áreas com saneamento precário",
        sazonalidade: "Pode aumentar durante estações chuvosas em algumas regiões",
        resistencia: "Algumas cepas têm mostrado resistência ao metronidazol"
    },
    {
        nome: "Gonorreia",
        outros: "Blenorragia",
        agentes: "Neisseria gonorrhoeae",
        tipoAgente: "Bactéria gram-negativa (diplococo)",
        descricao: "Doença sexualmente transmissível que infecta as mucosas urogenital, anal e orofaríngea. Diagnóstico por cultura e testes de amplificação de ácidos nucleicos. Possíveis complicações incluem doença inflamatória pélvica, infertilidade e disseminação sistêmica. Notificação compulsória: (SIM)",
        periodoIncubacao: "2 - 7 dias",
        transmissao: "Contato sexual, transmissão vertical durante o parto",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Corrimento uretral ou vaginal, dor ao urinar, dor abdominal inferior (em mulheres), pode ser assintomática",
        tratamento: "Antibióticos (ceftriaxona e azitromicina)",
        prevencao: "Uso de preservativos, exames regulares, tratamento de parceiros sexuais",
        gruposRisco: "Jovens sexualmente ativos, homens que fazem sexo com homens, profissionais do sexo",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Aumento preocupante de cepas resistentes a múltiplos antibióticos"
    },
    {
        nome: "Gripe",
        outros: "Influenza",
        agentes: "Vírus influenza A, Vírus influenza B, Vírus influenza C",
        tipoAgente: "Vírus RNA envelopado",
        descricao: "Doença respiratória aguda caracterizada por febre, tosse, dor de garganta e coriza. Diagnóstico clínico, confirmado por testes rápidos ou RT-PCR. Possíveis complicações incluem pneumonia, miocardite e agravamento de doenças crônicas. Notificação compulsória: (SIM, para casos graves)",
        periodoIncubacao: "1 - 4 dias",
        transmissao: "Gotículas respiratórias, contato com superfícies contaminadas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos, aves aquáticas (influenza A)",
        sintomas: "Febre, tosse, dor de garganta, coriza, mialgia, fadiga, cefaleia",
        tratamento: "Antivirais (oseltamivir, zanamivir em casos graves), repouso, hidratação",
        prevencao: "Vacinação anual, higiene das mãos, etiqueta respiratória",
        gruposRisco: "Idosos, crianças menores de 5 anos, gestantes, pessoas com doenças crônicas",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Maior incidência no inverno em climas temperados",
        resistencia: "Algumas cepas têm desenvolvido resistência a antivirais"
    },
    {
        nome: "Hanseníase",
        outros: "Lepra",
        agentes: "Mycobacterium leprae",
        tipoAgente: "Bacilo gram-positivo álcool-ácido resistente",
        descricao: "Doença infecciosa crônica que afeta principalmente a pele, os nervos periféricos, a mucosa do trato respiratório superior e os olhos. Diagnóstico clínico, confirmado por baciloscopia e biópsia de pele. Possíveis complicações incluem deformidades, cegueira e amputações. Notificação compulsória: (SIM)",
        periodoIncubacao: "2 - 7 anos (média de 5 anos)",
        transmissao: "Contato prolongado com secreções nasais e lesões de pele de pessoas não tratadas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Manchas na pele com perda de sensibilidade, dormência, fraqueza muscular, lesões nos nervos",
        tratamento: "Poliquimioterapia (PQT) com rifampicina, dapsona e clofazimina",
        prevencao: "Diagnóstico precoce, tratamento dos casos, vigilância dos contatos",
        gruposRisco: "Contatos domiciliares de pacientes não tratados",
        distribuicaoGeografica: "Prevalente em países tropicais e subtropicais, principalmente Índia, Brasil e Indonésia",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Casos raros de resistência aos medicamentos da PQT têm sido relatados"
    },
    {
        nome: "Herpes Genital",
        outros: "Herpes simplex genital",
        agentes: "Vírus Herpes Simplex tipo 2 (HSV-2), ocasionalmente HSV-1",
        tipoAgente: "Vírus DNA envelopado",
        descricao: "Infecção sexualmente transmissível que causa feridas dolorosas nos órgãos genitais. Diagnóstico clínico, confirmado por PCR ou cultura viral. Possíveis complicações incluem herpes neonatal, aumento do risco de aquisição e transmissão do HIV. Notificação compulsória: (NÃO)",
        periodoIncubacao: "2 - 12 dias",
        transmissao: "Contato sexual, transmissão vertical durante o parto",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Lesões vesiculares dolorosas nos órgãos genitais, febre, mal-estar, linfadenopatia inguinal",
        tratamento: "Antivirais (aciclovir, valaciclovir), tratamento sintomático",
        prevencao: "Uso de preservativo, abstinência durante surtos, terapia supressiva em casos recorrentes",
        gruposRisco: "Pessoas sexualmente ativas, especialmente com múltiplos parceiros",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Resistência ao aciclovir é rara, mas pode ocorrer, especialmente em pacientes imunocomprometidos"
    },
    {
        nome: "Herpes Labial",
        outros: "Herpes oral, Herpes simplex labial",
        agentes: "Vírus Herpes Simplex tipo 1 (HSV-1), ocasionalmente HSV-2",
        tipoAgente: "Vírus DNA envelopado",
        descricao: "Infecção viral que causa feridas dolorosas nos lábios e ao redor da boca. Diagnóstico geralmente clínico. Possíveis complicações incluem disseminação para outras partes do corpo e infecções secundárias. Notificação compulsória: (NÃO)",
        periodoIncubacao: "2 - 12 dias",
        transmissao: "Contato direto com as lesões, saliva, objetos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Coceira, formigamento, pequenas bolhas que se rompem e formam feridas, febre baixa",
        tratamento: "Antivirais tópicos ou orais (aciclovir, penciclovir), tratamento sintomático",
        prevencao: "Evitar contato com lesões ativas, não compartilhar objetos pessoais",
        gruposRisco: "Pessoas com sistema imunológico comprometido",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Pode ser desencadeado por estresse, febre, exposição solar",
        resistencia: "Resistência ao aciclovir é rara em imunocompetentes"
    },
    {
        nome: "Herpes Zoster",
        outros: "Cobreiro",
        agentes: "Vírus Varicela-Zoster (VZV)",
        tipoAgente: "Vírus DNA envelopado",
        descricao: "Reativação do vírus da varicela, caracterizada por erupção cutânea dolorosa em um dermátomo. Diagnóstico geralmente clínico, confirmado por PCR se necessário. Possíveis complicações incluem neuralgia pós-herpética, encefalite e disseminação cutânea. Notificação compulsória: (NÃO)",
        periodoIncubacao: "Não aplicável (reativação de infecção latente)",
        transmissao: "Contato com lesões vesiculares (pode causar varicela em pessoas suscetíveis)",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Dor, coceira, erupção cutânea com vesículas em um dermátomo, febre",
        tratamento: "Antivirais (aciclovir, valaciclovir), analgésicos, cuidados com a pele",
        prevencao: "Vacina contra o zoster para pessoas acima de 50 anos",
        gruposRisco: "Idosos, pessoas com sistema imunológico comprometido",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Resistência aos antivirais é rara"
    },
    {
        nome: "Histoplasmose",
        outros: "Doença de Darling",
        agentes: "Histoplasma capsulatum",
        tipoAgente: "Fungo dimórfico",
        descricao: "Doença fúngica sistêmica causada pela inalação de esporos, afetando principalmente os pulmões. Diagnóstico por cultura, histopatologia e sorologia. Possíveis complicações incluem disseminação para outros órgãos e síndrome de dificuldade respiratória aguda. Notificação compulsória: (NÃO)",
        periodoIncubacao: "3 - 17 dias",
        transmissao: "Inalação de esporos presentes em ambientes contaminados por excrementos de aves e morcegos",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo contaminado com excrementos de aves e morcegos",
        sintomas: "Febre, tosse, dor torácica, fadiga, perda de peso",
        tratamento: "Antifúngicos (itraconazol, anfotericina B)",
        prevencao: "Evitar ambientes contaminados, uso de máscaras em áreas de risco",
        gruposRisco: "Espeleólogos, trabalhadores rurais, pessoas com HIV/AIDS",
        distribuicaoGeografica: "Prevalente nas Américas, especialmente no vale do rio Mississippi (EUA)",
        sazonalidade: "Maior incidência no outono e inverno em algumas regiões",
        resistencia: "Geralmente sensível aos antifúngicos recomendados"
    },
    {
        nome: "HIV/AIDS",
        outros: "Síndrome da Imunodeficiência Adquirida",
        agentes: "Vírus da Imunodeficiência Humana (HIV-1 e HIV-2)",
        tipoAgente: "Retrovírus (vírus RNA)",
        descricao: "Doença infecciosa crônica que ataca o sistema imunológico, deixando o indivíduo mais suscetível a infecções oportunistas e certos tipos de câncer. Diagnóstico por testes sorológicos e confirmação por Western blot ou PCR. Notificação compulsória: (SIM)",
        periodoIncubacao: "2 - 4 semanas para infecção aguda, anos para AIDS",
        transmissao: "Relações sexuais desprotegidas, compartilhamento de agulhas, transmissão vertical (mãe para filho)",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Fase aguda: febre, fadiga, erupção cutânea; Fase crônica: perda de peso, infecções oportunistas",
        tratamento: "Terapia antirretroviral (TARV)",
        prevencao: "Uso de preservativo, PrEP, PEP, não compartilhamento de agulhas, tratamento como prevenção",
        gruposRisco: "Homens que fazem sexo com homens, usuários de drogas injetáveis, profissionais do sexo",
        distribuicaoGeografica: "Mundial, com maior prevalência na África Subsaariana",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Resistência a antirretrovirais pode ocorrer, necessitando mudanças no esquema terapêutico"
    },
    {
        nome: "HPV",
        outros: "Papilomavírus Humano",
        agentes: "Diferentes tipos de HPV (mais de 200 tipos identificados)",
        tipoAgente: "Vírus DNA não envelopado",
        descricao: "Infecção sexualmente transmissível que pode causar verrugas genitais e câncer, principalmente do colo do útero. Diagnóstico por exame citológico (Papanicolaou), colposcopia, teste de DNA viral. Possíveis complicações incluem câncer cervical, anal, de pênis e orofaríngeo. Notificação compulsória: (NÃO)",
        periodoIncubacao: "3 semanas a 8 meses (média de 3 meses)",
        transmissao: "Contato sexual, contato pele a pele com lesões",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Geralmente assintomático; pode causar verrugas genitais, lesões pré-cancerosas, câncer",
        tratamento: "Remoção das verrugas, tratamento das lesões pré-cancerosas, tratamento do câncer se desenvolvido",
        prevencao: "Vacina contra o HPV, uso de preservativo, exames ginecológicos regulares",
        gruposRisco: "Pessoas sexualmente ativas, especialmente jovens",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Não aplicável (infecção viral sem tratamento específico)"
    },
    {
        nome: "Leishmaniose",
        outros: "Leishmaniose tegumentar, Leishmaniose visceral (Calazar)",
        agentes: "Várias espécies de Leishmania",
        tipoAgente: "Protozoário flagelado",
        descricao: "Doença parasitária que pode afetar a pele, as mucosas ou os órgãos internos. Diagnóstico por exame parasitológico direto, cultura, sorologia ou PCR. Possíveis complicações incluem destruição de tecidos, falência de órgãos na forma visceral. Notificação compulsória: (SIM)",
        periodoIncubacao: "10 dias a 24 meses",
        transmissao: "Picada de flebotomíneos (mosquito-palha) infectados",
        definitivo: "Humanos e outros mamíferos",
        intermediario: "Flebotomíneos",
        reservatorio: "Varia conforme a espécie: cães, roedores, marsupiais",
        sintomas: "Forma cutânea: úlceras na pele; Forma visceral: febre, perda de peso, hepatoesplenomegalia",
        tratamento: "Antimoniais pentavalentes, anfotericina B, miltefosina",
        prevencao: "Controle de vetores, uso de repelentes, proteção de telas em janelas",
        gruposRisco: "Pessoas que vivem ou trabalham em áreas endêmicas",
        distribuicaoGeografica: "Regiões tropicais e subtropicais da África, Ásia, América do Sul, sul da Europa",
        sazonalidade: "Pode variar conforme a região, geralmente mais comum em estações quentes",
        resistencia: "Resistência aos antimoniais tem sido relatada em algumas regiões"
    },
    {
        nome: "Malária",
        outros: "Paludismo, Febre palustre",
        agentes: "Plasmodium falciparum, P. vivax, P. ovale, P. malariae, P. knowlesi",
        tipoAgente: "Protozoário",
        descricao: "Doença infecciosa febril aguda causada por protozoários do gênero Plasmodium. Diagnóstico por exame de gota espessa, testes rápidos ou PCR. Possíveis complicações incluem malária cerebral, insuficiência renal aguda, anemia grave. Notificação compulsória: (SIM)",
        periodoIncubacao: "7 - 30 dias (varia conforme a espécie)",
        transmissao: "Picada de mosquitos Anopheles fêmea infectados",
        definitivo: "Humanos",
        intermediario: "Mosquito Anopheles",
        reservatorio: "Humanos (principal), alguns primatas para certas espécies",
        sintomas: "Febre, calafrios, sudorese, dor de cabeça, náuseas, vômitos, fadiga",
        tratamento: "Antimaláricos específicos conforme a espécie (ex: artemisina, cloroquina)",
        prevencao: "Uso de repelentes, mosquiteiros impregnados, controle vetorial, quimioprofilaxia para viajantes",
        gruposRisco: "Crianças menores de 5 anos, gestantes, viajantes não imunes",
        distribuicaoGeografica: "Regiões tropicais e subtropicais, principalmente África Subsaariana",
        sazonalidade: "Maior incidência em estações chuvosas em áreas endêmicas",
        resistencia: "P. falciparum tem desenvolvido resistência a vários antimaláricos"
    },
    {
        nome: "Meningite",
        outros: "Meningite bacteriana, viral, fúngica",
        agentes: "Vários, como Neisseria meningitidis, Streptococcus pneumoniae, vírus entéricos",
        tipoAgente: "Bactérias, vírus, fungos",
        descricao: "Inflamação das meninges, membranas que revestem o cérebro e a medula espinhal. Diagnóstico por análise do líquor, cultura, PCR. Possíveis complicações incluem danos cerebrais, surdez, convulsões. Notificação compulsória: (SIM)",
        periodoIncubacao: "2 - 10 dias (bacteriana), 3 - 7 dias (viral)",
        transmissao: "Varia conforme o agente: gotículas respiratórias, contato próximo",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos, varia conforme o agente",
        sintomas: "Febre alta, rigidez na nuca, dor de cabeça intensa, vômitos, fotofobia",
        tratamento: "Antibióticos (bacteriana), antivirais (viral), antifúngicos (fúngica)",
        prevencao: "Vacinação (para alguns tipos), higiene das mãos, evitar contato próximo com doentes",
        gruposRisco: "Crianças, idosos, pessoas com sistema imunológico comprometido",
        distribuicaoGeografica: "Mundial, com variações na prevalência dos agentes",
        sazonalidade: "Meningite viral mais comum no verão; meningite bacteriana pode ter picos no inverno",
        resistencia: "Algumas bactérias têm desenvolvido resistência a antibióticos"
    },
    {
        nome: "Mucormicose",
        outros: "Zigomicose",
        agentes: "Fungos da ordem Mucorales (Rhizopus, Mucor, Rhizomucor)",
        tipoAgente: "Fungo filamentoso",
        descricao: "Infecção fúngica invasiva rara, mas grave, que afeta principalmente pessoas imunocomprometidas. Diagnóstico por biópsia e cultura. Possíveis complicações incluem trombose, necrose tecidual, morte. Notificação compulsória: (NÃO)",
        periodoIncubacao: "1 - 3 semanas",
        transmissao: "Inalação de esporos do fungo, inoculação direta em feridas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Ambiente (solo, matéria orgânica em decomposição)",
        sintomas: "Varia conforme o local afetado: sinusite, lesões cutâneas necróticas, sintomas pulmonares",
        tratamento: "Antifúngicos (anfotericina B), cirurgia para remoção de tecidos necróticos",
        prevencao: "Controle de doenças de base (diabetes, imunossupressão), evitar exposição a ambientes contaminados",
        gruposRisco: "Diabéticos descompensados, pessoas com neutropenia, pacientes em uso de corticosteroides",
        distribuicaoGeografica: "Mundial, mais comum em climas quentes e úmidos",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Geralmente sensível à anfotericina B"
    },
    {
        nome: "Paracoccidioidomicose",
        outros: "Blastomicose sul-americana",
        agentes: "Paracoccidioides brasiliensis, P. lutzii",
        tipoAgente: "Fungo dimórfico",
        descricao: "Micose sistêmica endêmica na América Latina, que acomete principalmente os pulmões, mucosa oral e pele. Diagnóstico por exame direto, cultura, histopatologia e sorologia. Possíveis complicações incluem fibrose pulmonar e insuficiência respiratória. Notificação compulsória: (SIM, em alguns estados)",
        periodoIncubacao: "Meses a anos",
        transmissao: "Inalação de conídios presentes no solo",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo",
        sintomas: "Lesões na mucosa oral, tosse, dispneia, perda de peso, linfadenopatia",
        tratamento: "Antifúngicos (itraconazol, anfotericina B)",
        prevencao: "Evitar exposição a poeira em áreas endêmicas, uso de máscaras em atividades de risco",
        gruposRisco: "Trabalhadores rurais, fumantes",
        distribuicaoGeografica: "América Latina, principalmente Brasil, Colômbia e Venezuela",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Geralmente sensível aos antifúngicos recomendados"
    },
    {
        nome: "Pitiríase versicolor",
        outros: "Tinha versicolor",
        agentes: "Malassezia furfur, M. globosa, M. sympodialis",
        tipoAgente: "Fungo leveduriforme",
        descricao: "Infecção fúngica superficial da pele que causa manchas descoloridas. Diagnóstico clínico, confirmado por exame microscópico direto. Possíveis complicações são raras, mas podem incluir alterações pigmentares persistentes. Notificação compulsória: (NÃO)",
        periodoIncubacao: "10 - 14 dias",
        transmissao: "Contato direto com a pele de pessoas infectadas ou objetos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos (o fungo faz parte da microbiota normal da pele)",
        sintomas: "Manchas brancas, rosadas ou marrons na pele, principalmente no tronco e nos braços, leve descamação",
        tratamento: "Antifúngicos tópicos (cetoconazol, terbinafina) ou orais em casos extensos",
        prevencao: "Manter a pele limpa e seca, evitar o uso de roupas apertadas e suadas",
        gruposRisco: "Adolescentes e adultos jovens, pessoas que vivem em climas quentes e úmidos",
        distribuicaoGeografica: "Mundial, mais comum em regiões tropicais e subtropicais",
        sazonalidade: "Mais frequente em épocas quentes e úmidas",
        resistencia: "Geralmente sensível aos antifúngicos tópicos comuns"
    },
    {
        nome: "Pneumonia Bacteriana",
        outros: "Pneumonia adquirida na comunidade",
        agentes: "Streptococcus pneumoniae, Haemophilus influenzae, Staphylococcus aureus, entre outros",
        tipoAgente: "Bactérias",
        descricao: "Infecção aguda do parênquima pulmonar, geralmente causada por bactérias. Diagnóstico por exame clínico, radiografia de tórax e exames laboratoriais. Possíveis complicações incluem sepse, insuficiência respiratória e derrame pleural. Notificação compulsória: (NÃO, exceto em surtos)",
        periodoIncubacao: "1 - 3 dias",
        transmissao: "Inalação de gotículas respiratórias contendo os agentes infecciosos",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Febre, tosse com expectoração, dor torácica, dispneia, fadiga",
        tratamento: "Antibióticos (escolha baseada no agente suspeito e antibiograma)",
        prevencao: "Vacinação contra pneumococo e influenza, higiene das mãos, cessação do tabagismo",
        gruposRisco: "Idosos, crianças menores de 5 anos, pessoas com doenças crônicas, fumantes",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Mais comum no inverno e início da primavera em climas temperados",
        resistencia: "Aumento da resistência aos antibióticos, especialmente em S. pneumoniae e S. aureus"
    },
    {
        nome: "Sarampo",
        outros: "Rubeola",
        agentes: "Vírus do sarampo (gênero Morbillivirus)",
        tipoAgente: "Vírus RNA",
        descricao: "Doença infecciosa aguda, altamente contagiosa, caracterizada por febre alta, manchas vermelhas na pele e sintomas respiratórios. Diagnóstico clínico, confirmado por sorologia ou PCR. Possíveis complicações incluem pneumonia, encefalite e panencefalite esclerosante subaguda. Notificação compulsória: (SIM)",
        periodoIncubacao: "7 - 14 dias",
        transmissao: "Gotículas respiratórias, contato direto com secreções nasais ou faríngeas de pessoas infectadas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Febre alta, tosse, coriza, conjuntivite, manchas de Koplik, exantema maculopapular",
        tratamento: "Tratamento de suporte, vitamina A",
        prevencao: "Vacinação (vacina tríplice viral - SCR)",
        gruposRisco: "Crianças não vacinadas, gestantes, pessoas com imunodeficiência",
        distribuicaoGeografica: "Mundial, com surtos em áreas com baixa cobertura vacinal",
        sazonalidade: "Picos no final do inverno e início da primavera em climas temperados",
        resistencia: "Não aplicável (doença viral sem tratamento específico)"
    },
    {
        nome: "Sífilis",
        outros: "Lues",
        agentes: "Treponema pallidum",
        tipoAgente: "Bactéria espiroqueta",
        descricao: "Doença sexualmente transmissível que pode afetar vários órgãos e sistemas do corpo. Diagnóstico por testes sorológicos (VDRL, FTA-ABS) e exame direto de lesões. Possíveis complicações incluem neurossífilis, sífilis cardiovascular e gomas sifilíticas. Notificação compulsória: (SIM)",
        periodoIncubacao: "10 - 90 dias (média de 21 dias)",
        transmissao: "Contato sexual, transmissão vertical (mãe para filho), raramente por transfusão sanguínea",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Varia conforme o estágio: cancro duro, erupção cutânea, condiloma plano, gomas sifilíticas",
        tratamento: "Penicilina benzatina (dose varia conforme o estágio da doença)",
        prevencao: "Uso de preservativo, testagem regular, tratamento de parceiros sexuais",
        gruposRisco: "Homens que fazem sexo com homens, profissionais do sexo, gestantes não tratadas",
        distribuicaoGeografica: "Mundial",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "T. pallidum permanece sensível à penicilina"
    },
    {
        nome: "Síndrome de Fournier",
        outros: "Gangrena de Fournier",
        agentes: "Polimicrobiana (Streptococcus, Staphylococcus, Enterobacteriaceae, anaeróbios)",
        tipoAgente: "Bactérias aeróbias e anaeróbias",
        descricao: "Fasciite necrotizante que afeta a região genital, perineal e perianal. Diagnóstico clínico, confirmado por exames de imagem e cultura de tecidos. Possíveis complicações incluem sepse, falência múltipla de órgãos e morte. Notificação compulsória: (NÃO)",
        periodoIncubacao: "2 - 7 dias",
        transmissao: "Não é transmissível entre pessoas; resulta da invasão de bactérias em tecidos profundos",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Não aplicável",
        sintomas: "Dor intensa, edema, eritema na região genital/perineal, febre, crepitação subcutânea",
        tratamento: "Antibióticos de amplo espectro, desbridamento cirúrgico, oxigenoterapia hiperbárica",
        prevencao: "Controle de fatores de risco (diabetes, obesidade), higiene adequada",
        gruposRisco: "Diabéticos, idosos, imunossuprimidos, alcoólatras",
        distribuicaoGeografica: "Mundial, mais comum em países em desenvolvimento",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Pode envolver bactérias multirresistentes, especialmente em ambiente hospitalar"
    },
    {
        nome: "Teníase",
        outros: "Solitária",
        agentes: "Taenia saginata, Taenia solium",
        tipoAgente: "Helminto (cestoda)",
        descricao: "Infecção intestinal causada por tênias adultas. Diagnóstico por exame parasitológico de fezes. Possíveis complicações incluem obstrução intestinal e, no caso de T. solium, cisticercose. Notificação compulsória: (NÃO)",
        periodoIncubacao: "8 - 14 semanas",
        transmissao: "Ingestão de carne crua ou mal cozida de bovinos (T. saginata) ou suínos (T. solium) contendo cisticercos",
        definitivo: "Humanos",
        intermediario: "Bovinos (T. saginata), suínos (T. solium)",
        reservatorio: "Humanos (para a forma adulta do parasita)",
        sintomas: "Geralmente assintomática, mas pode causar dor abdominal, náuseas, perda de peso, eliminação de proglotes",
        tratamento: "Anti-helmínticos (praziquantel, niclosamida)",
        prevencao: "Cozinhar bem a carne, inspeção sanitária de carnes, higiene das mãos",
        gruposRisco: "Pessoas que consomem carne crua ou mal cozida",
        distribuicaoGeografica: "Mundial, mais comum em áreas com criação de gado e suínos e saneamento precário",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Geralmente sensível aos anti-helmínticos recomendados"
    },
    {
        nome: "Tétano",
        outros: "Trismo",
        agentes: "Clostridium tetani",
        tipoAgente: "Bacilo gram-positivo formador de esporos",
        descricao: "Doença infecciosa aguda, não contagiosa, caracterizada por contrações musculares dolorosas. Diagnóstico clínico. Possíveis complicações incluem insuficiência respiratória, arritmias cardíacas e morte. Notificação compulsória: (SIM)",
        periodoIncubacao: "3 - 21 dias (média de 7 dias)",
        transmissao: "Introdução de esporos em feridas contaminadas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo, trato gastrointestinal de animais",
        sintomas: "Rigidez muscular, espasmos, trismo (mandíbula travada), opistótono, febre",
        tratamento: "Imunoglobulina antitetânica, antibióticos, cuidados de suporte",
        prevencao: "Vacinação (DTP, dT), limpeza e desinfecção adequada de ferimentos",
        gruposRisco: "Pessoas não vacinadas, idosos, usuários de drogas injetáveis",
        distribuicaoGeografica: "Mundial, mais comum em áreas com baixa cobertura vacinal",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "C. tetani permanece sensível aos antibióticos recomendados"
    },
    {
        nome: "Tracoma",
        outros: "Conjuntivite por Chlamydia",
        agentes: "Chlamydia trachomatis (sorotipos A, B, Ba e C)",
        tipoAgente: "Bactéria intracelular obrigatória",
        descricao: "Infecção ocular crônica que pode levar à cegueira. Diagnóstico clínico, confirmado por testes laboratoriais (PCR, imunofluorescência direta). Possíveis complicações incluem cicatrização conjuntival, entrópio e opacificação da córnea. Notificação compulsória: (SIM)",
        periodoIncubacao: "5 - 12 dias",
        transmissao: "Contato direto com secreções oculares de pessoas infectadas, objetos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Irritação ocular, fotofobia, secreção ocular, folículos na conjuntiva tarsal superior",
        tratamento: "Antibióticos (azitromicina oral ou tetraciclina tópica)",
        prevencao: "Higiene facial, acesso à água limpa, saneamento básico, estratégia SAFE (cirurgia, antibióticos, limpeza facial, melhorias ambientais)",
        gruposRisco: "Crianças em áreas endêmicas, pessoas vivendo em condições precárias de higiene",
        distribuicaoGeografica: "Áreas com saneamento precário na África, Oriente Médio, subcontinente indiano",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Não há relatos significativos de resistência aos antibióticos recomendados"
    },
    {
        nome: "Tuberculose",
        outros: "TB",
        agentes: "Mycobacterium tuberculosis",
        tipoAgente: "Bacilo álcool-ácido resistente",
        descricao: "Doença infecciosa crônica que afeta principalmente os pulmões, mas pode atingir outros órgãos. Diagnóstico por baciloscopia, cultura, teste molecular rápido. Possíveis complicações incluem insuficiência respiratória, derrame pleural e disseminação extrapulmonar. Notificação compulsória: (SIM)",
        periodoIncubacao: "4 - 12 semanas",
        transmissao: "Via aérea, através de gotículas respiratórias",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Tosse persistente, febre, perda de peso, sudorese noturna, fadiga",
        tratamento: "Esquema RHZE (rifampicina, isoniazida, pirazinamida, etambutol) por 6 meses",
        prevencao: "Vacinação BCG, diagnóstico precoce e tratamento, ventilação adequada",
        gruposRisco: "Pessoas vivendo com HIV, diabéticos, usuários de drogas, população carcerária",
        distribuicaoGeografica: "Mundial, com maior incidência em países em desenvolvimento",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Aumento preocupante de cepas multirresistentes (MDR-TB) e extensivamente resistentes (XDR-TB)"
    },
    {
        nome: "Varíola do Macaco",
        outros: "Monkeypox",
        agentes: "Vírus da varíola do macaco (gênero Orthopoxvirus)",
        tipoAgente: "Vírus DNA envelopado",
        descricao: "Doença zoonótica viral que causa erupção cutânea e sintomas sistêmicos. Diagnóstico por PCR de material das lesões. Possíveis complicações incluem pneumonite, encefalite e infecções secundárias. Notificação compulsória: (SIM)",
        periodoIncubacao: "5 - 21 dias",
        transmissao: "Contato próximo com lesões, fluidos corporais, gotículas respiratórias de pessoas ou animais infectados",
        definitivo: "Humanos e vários animais",
        intermediario: "Não aplicável",
        reservatorio: "Roedores africanos, primatas não humanos",
        sintomas: "Febre, dor de cabeça, mialgia, linfadenopatia, erupção cutânea com vesículas e pústulas",
        tratamento: "Geralmente sintomático; antivirais (tecovirimat) em casos graves",
        prevencao: "Evitar contato com animais ou pessoas infectadas, vacina contra varíola pode oferecer alguma proteção",
        gruposRisco: "Homens que fazem sexo com homens, profissionais de saúde, pessoas que manipulam animais em áreas endêmicas",
        distribuicaoGeografica: "Endêmica na África Central e Ocidental, surtos recentes em vários países",
        sazonalidade: "Sem padrão sazonal específico",
        resistencia: "Não há relatos significativos de resistência aos antivirais"
    },
    {
        nome: "Zika",
        outros: "Febre Zika",
        agentes: "Vírus Zika",
        tipoAgente: "Vírus RNA (flavivírus)",
        descricao: "Doença viral transmitida por mosquitos, geralmente leve, mas associada a complicações neurológicas em fetos. Diagnóstico por RT-PCR e sorologia. Possíveis complicações incluem microcefalia em recém-nascidos e síndrome de Guillain-Barré. Notificação compulsória: (SIM)",
        periodoIncubacao: "3 - 14 dias",
        transmissao: "Picada do mosquito Aedes aegypti infectado, transmissão sexual, vertical (mãe para feto)",
        definitivo: "Humanos",
        intermediario: "Mosquito Aedes aegypti",
        reservatorio: "Humanos, possivelmente primatas não humanos",
        sintomas: "Febre baixa, erupção cutânea, conjuntivite, dores nas articulações, dores musculares",
        tratamento: "Sintomático (repouso, hidratação, analgésicos)",
        prevencao: "Combate ao mosquito transmissor, uso de repelentes, proteção durante relações sexuais",
        gruposRisco: "Gestantes, devido ao risco de malformações fetais",
        distribuicaoGeografica: "Regiões tropicais e subtropicais, principalmente Américas e algumas ilhas do Pacífico",
        sazonalidade: "Maior incidência em épocas quentes e chuvosas",
        resistencia: "Não aplicável (doença viral sem tratamento específico)"
    }
];