let dados = [
    {
        nome: "COVID-19",
        outros: "Doença por coronavírus 2019",
        agentes: "SARS-CoV-2",
        tipoAgente: "vírus RNA envelopado",
        descricao: "Doença infecciosa causada por um novo coronavírus, com sintomas que podem variar de leves a graves, incluindo febre, tosse, fadiga e dificuldade para respirar.",
        periodoIncubacao: "2 - 14 dias",
        transmissao: "Gotículas respiratórias, contato com superfícies contaminadas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Ainda sob investigação",
        sintomas: "Febre, Tosse, Fadiga, Perda de olfato e paladar, Dificuldade para respirar",
        tratamento: "Tratamento dos sintomas, remédios antivirais em casos graves",
        prevencao: "Vacinação, uso de máscara, higiene das mãos, distanciamento social"
    },
    {
        nome: "Teníase",
        outros: "Solitária",
        agentes: "Taenia saginata, Taenia solium",
        tipoAgente: "helminto (cestoda)",
        descricao: "Doença parasitária causada pela ingestão de carne crua ou mal cozida de bovinos (T. saginata) ou suínos (T. solium) contendo cisticercos.",
        periodoIncubacao: "2 - 3 meses",
        transmissao: "Ingestão de carne crua ou mal cozida",
        definitivo: "Humanos",
        intermediario: "Bovinos (T. saginata), suínos (T. solium)",
        sintomas: "Geralmente assintomática, mas pode causar dor abdominal, náuseas, perda de peso",
        tratamento: "Medicamentos antiparasitários",
        prevencao: "Cozinhar bem a carne, higiene das mãos"
    },
    {
        nome: "Cisticercose",
        outros: "Cisticercose cerebral",
        agentes: "Taenia solium",
        tipoAgente: "helminto (cestoda)",
        descricao: "Doença parasitária causada pela ingestão de ovos de Taenia solium, que se desenvolvem em larvas (cisticercos) em diversos órgãos do corpo humano.",
        periodoIncubacao: "Varia de acordo com o local da infecção",
        transmissao: "Ingestão de alimentos ou água contaminados com ovos de T. solium",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Sintomas variam de acordo com o local da infecção, mas podem incluir dores de cabeça, convulsões, alterações visuais",
        tratamento: "Tratamento cirúrgico e medicamentos antiparasitários",
        prevencao: "Higiene das mãos, saneamento básico, tratamento adequado da teníase"
    },
    {
        nome: "Tétano",
        outros: "Lockjaw",
        agentes: "Clostridium tetani",
        tipoAgente: "bacilo gram positivo",
        descricao: "Doença infecciosa aguda, caracterizada por contrações musculares espasmódicas e dolorosas.",
        periodoIncubacao: "3 - 21 dias",
        transmissao: "Contaminação de ferimentos com esporos da bactéria",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo, trato gastrointestinal de animais",
        sintomas: "Espasmos musculares, rigidez muscular, dificuldade para engolir, febre",
        tratamento: "Imunoglobulina antitetânica, antibióticos, cuidados de suporte",
        prevencao: "Vacinação, limpeza e desinfecção de ferimentos"
    },
    {
        nome: "HIV/AIDS",
        outros: "Síndrome da Imunodeficiência Adquirida",
        agentes: "Vírus da Imunodeficiência Humana (HIV)",
        tipoAgente: "vírus RNA",
        descricao: "Doença infecciosa crônica que ataca o sistema imunológico, deixando o indivíduo mais suscetível a outras infecções.",
        periodoIncubacao: "Varia, pode ser assintomática por anos",
        transmissao: "Relações sexuais desprotegidas, compartilhamento de agulhas, transmissão vertical (mãe para filho)",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Febre, fadiga, perda de peso, infecções oportunistas",
        tratamento: "Terapia antirretroviral",
        prevencao: "Uso de preservativo, testes regulares, não compartilhamento de agulhas"
    },
    {
        nome: "Malária",
        outros: "Febre palustre",
        agentes: "Plasmodium falciparum, Plasmodium vivax, Plasmodium ovale, Plasmodium malariae",
        tipoAgente: "protozoário",
        descricao: "Doença infecciosa transmitida por mosquitos, causando febre, calafrios e outros sintomas.",
        periodoIncubacao: "7 - 30 dias",
        transmissao: "Picada do mosquito Anopheles infectado",
        definitivo: "Humanos",
        intermediario: "Mosquito Anopheles",
        reservatorio: "Humanos e mosquitos",
        sintomas: "Febre, calafrios, suor, dor de cabeça, náuseas, vômitos",
        tratamento: "Antimaláricos",
        prevencao: "Uso de repelentes, mosquiteiros, controle de vetores"
    },
    {
        nome: "Gripe",
        outros: "Influenza",
        agentes: "Vírus influenza A, Vírus influenza B, Vírus influenza C",
        tipoAgente: "vírus RNA envelopado",
        descricao: "Doença respiratória aguda caracterizada por febre, tosse, dor de garganta e coriza.",
        periodoIncubacao: "1 - 4 dias",
        transmissao: "Gotículas respiratórias",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Aves aquáticas (influenza A)",
        sintomas: "Febre, Tosse, Dor de garganta, Coriza, Mialgia, Fadiga",
        tratamento: "Antivirais (em casos graves), repouso, hidratação",
        prevencao: "Vacinação anual, higiene das mãos, cobertura da boca ao tossir ou espirrar"
    },
    {
        nome: "Tuberculose",
        outros: "TB",
        agentes: "Mycobacterium tuberculosis",
        tipoAgente: "bacilo gram positivo",
        descricao: "Doença infecciosa crônica que afeta principalmente os pulmões, mas pode atingir outros órgãos.",
        periodoIncubacao: "4 - 12 semanas",
        transmissao: "Via aérea, através de gotículas respiratórias",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Tosse persistente, febre, perda de peso, suor noturno",
        tratamento: "Tratamento com antibióticos por um longo período",
        prevencao: "Vacinação (BCG), diagnóstico precoce e tratamento, ventilação adequada em ambientes fechados"
    },
    {
        nome: "Meningite",
        outros: "Inflamação das meninges",
        agentes: "Vários, como Streptococcus pneumoniae, Neisseria meningitidis, Haemophilus influenzae",
        tipoAgente: "Bactérias, vírus, fungos",
        descricao: "Inflamação das meninges, membranas que revestem o cérebro e a medula espinhal.",
        periodoIncubacao: "Varia de acordo com o agente causador",
        transmissao: "Direta (contato com secreções respiratórias) ou indireta (contato com objetos contaminados)",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Rigidez na nuca, febre alta, dor de cabeça intensa, vômitos",
        tratamento: "Antibióticos (em casos bacterianos), antivirais (em casos virais), antifúngicos (em casos fúngicos)",
        prevencao: "Vacinação, higiene das mãos, cobertura da boca ao tossir ou espirrar"
    },
    {
        nome: "Sífilis",
        outros: "Lues",
        agentes: "Treponema pallidum",
        tipoAgente: "espiroqueta",
        descricao: "Doença sexualmente transmissível causada por uma bactéria, que pode afetar vários órgãos e sistemas do corpo.",
        periodoIncubacao: "10 - 90 dias",
        transmissao: "Relações sexuais desprotegidas, contato com lesões, transmissão vertical (mãe para filho)",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Úlcera indolor nos órgãos genitais, erupção cutânea, febre, perda de peso",
        tratamento: "Antibióticos (penicilina)",
        prevencao: "Uso de preservativo, testes regulares, tratamento de parceiros sexuais"
    },
    {
        nome: "Cólera",
        outros: "Cólera epidêmica",
        agentes: "Vibrio cholerae",
        tipoAgente: "vibrião gram negativo",
        descricao: "Doença infecciosa aguda do intestino delgado, causada pela ingestão de água ou alimentos contaminados.",
        periodoIncubacao: "2 horas a 5 dias",
        transmissao: "Fecal-oral, através de água ou alimentos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Água e alimentos contaminados",
        sintomas: "Diarreia aquosa intensa, vômitos, desidratação",
        tratamento: "Reposição de líquidos e eletrólitos, antibióticos",
        prevencao: "Saneamento básico, higiene pessoal, tratamento de água e alimentos"
    },
    {
        nome: "Dengue",
        outros: "Febre quebra ossos",
        agentes: "Vírus da dengue",
        tipoAgente: "vírus RNA",
        descricao: "Doença infecciosa transmitida por mosquitos, caracterizada por febre alta, dores no corpo, dor de cabeça e erupção cutânea.",
        periodoIncubacao: "3 - 14 dias",
        transmissao: "Picada do mosquito Aedes aegypti",
        definitivo: "Humanos",
        intermediario: "Mosquito Aedes aegypti",
        reservatorio: "Humanos",
        sintomas: "Febre alta, dor de cabeça, dores musculares e articulares, erupção cutânea, náuseas, vômitos",
        tratamento: "Sintomático (repouso, hidratação)",
        prevencao: "Combate ao mosquito transmissor, uso de repelentes, telas em janelas"
    },
    {
        nome: "Zika",
        outros: "Zyka",
        agentes: "Vírus Zika",
        tipoAgente: "vírus RNA",
        descricao: "Doença infecciosa transmitida por mosquitos, associada a microcefalia em recém-nascidos e síndrome de Guillain-Barré.",
        periodoIncubacao: "3 - 14 dias",
        transmissao: "Picada do mosquito Aedes aegypti",
        definitivo: "Humanos",
        intermediario: "Mosquito Aedes aegypti",
        reservatorio: "Humanos",
        sintomas: "Febre baixa, erupção cutânea, conjuntivite, dores nas articulações, dores musculares",
        tratamento: "Sintomático",
        prevencao: "Combate ao mosquito transmissor, uso de repelentes, telas em janelas"
    },
    {
        nome: "HIV/AIDS",
        outros: "Síndrome da Imunodeficiência Adquirida",
        agentes: "Vírus da Imunodeficiência Humana (HIV)",
        tipoAgente: "vírus RNA - retrovírus",
        descricao: "Doença infecciosa crônica que ataca o sistema imunológico, deixando o indivíduo mais suscetível a outras infecções.",
        periodoIncubacao: "Varia, pode ser assintomática por anos",
        transmissao: "Relações sexuais desprotegidas, compartilhamento de agulhas, transmissão vertical (mãe para filho)",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Febre, fadiga, perda de peso, infecções oportunistas",
        tratamento: "Terapia antirretroviral",
        prevencao: "Uso de preservativo, testes regulares, não compartilhamento de agulhas"
    },
    {
        nome: "Sarampo",
        outros: "não tem",
        agentes: "Vírus do sarampo",
        tipoAgente: "vírus RNA",
        descricao: "Doença infecciosa aguda, altamente contagiosa, caracterizada por febre alta, manchas vermelhas na pele e tosse.",
        periodoIncubacao: "10 - 14 dias",
        transmissao: "Gotículas respiratórias",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Febre alta, tosse, coriza, conjuntivite, manchas vermelhas na pele",
        tratamento: "Sintomático",
        prevencao: "Vacinação"
    },
    {
        nome: "Malária",
        outros: "Febre palustre",
        agentes: "Plasmodium falciparum, Plasmodium vivax, Plasmodium ovale, Plasmodium malariae",
        tipoAgente: "protozoário",
        descricao: "Doença infecciosa transmitida por mosquitos, causando febre, calafrios e outros sintomas.",
        periodoIncubacao: "7 - 30 dias",
        transmissao: "Picada do mosquito Anopheles infectado",
        definitivo: "Humanos",
        intermediario: "Mosquito Anopheles",
        reservatorio: "Humanos e mosquitos",
        sintomas: "Febre, calafrios, suor, dor de cabeça, náuseas, vômitos",
        tratamento: "Antimaláricos",
        prevencao: "Uso de repelentes, mosquiteiros, controle de vetores"
    },
    {
        nome: "Leishmaniose",
        outros: "Úlcera de Bauru",
        agentes: "Leishmania spp.",
        tipoAgente: "protozoário",
        descricao: "Doença infecciosa causada por protozoários do gênero Leishmania, que pode afetar a pele, as mucosas ou os órgãos internos.",
        periodoIncubacao: "Varia, geralmente semanas ou meses",
        transmissao: "Picada de insetos flebótomos infectados",
        definitivo: "Humanos",
        intermediario: "Insetos flebótomos",
        reservatorio: "Cães domésticos, gambás, roedores e outros animais silvestres",
        sintomas: "Úlceras cutâneas, febre, aumento de gânglios linfáticos",
        tratamento: "Medicamentos antiparasitários",
        prevencao: "Controle de vetores, uso de repelentes, proteção da pele"
    },
    {
        nome: "Esquistossomose",
        outros: "Barriga d'água",
        agentes: "Schistosoma mansoni, Schistosoma haematobium, Schistosoma japonicum",
        tipoAgente: "helminto",
        descricao: "Doença parasitária causada por vermes platelmintos, que afetam principalmente o fígado e os intestinos.",
        periodoIncubacao: "Semanas a meses",
        transmissao: "Penetração ativa das larvas cercárias através da pele, durante o contato com água doce contaminada",
        definitivo: "Humanos",
        intermediario: "Caramujos aquáticos",
        reservatorio: "Humanos",
        sintomas: "Coceira no local de penetração, febre, dor abdominal, diarreia, hepatomegalia, esplenomegalia",
        tratamento: "Medicamentos antiparasitários",
        prevencao: "Saneamento básico, educação em saúde, controle de vetores"
    },
    {
        nome: "Giardíase",
        outros: "não tem",
        agentes: "Giardia lamblia",
        tipoAgente: "protozoário",
        descricao: "Doença infecciosa causada por um protozoário, afetando principalmente o intestino delgado.",
        periodoIncubacao: "1 - 2 semanas",
        transmissao: "Fecal-oral, através de água ou alimentos contaminados",
        definitivo: "Humanos",
        reservatorio: "Animais",
        reservatorio: "Humanos, cães domésticos e outros animais.",
        sintomas: "Diarreia, dores abdominais, flatulência, perda de peso",
        tratamento: "Medicamentos antiparasitários",
        prevencao: "Higiene pessoal, tratamento de água e alimentos, saneamento básico"
    },
    {
        nome: "Botulismo",
        outros: "Intoxicação botulínica",
        agentes: "Clostridium botulinum",
        tipoAgente: "bacilo gram positivo formador de esporos",
        descricao: "Doença neurotóxica grave causada pela ingestão de alimentos contaminados pela neurotoxina botulínica.",
        periodoIncubacao: "12 - 36 horas",
        transmissao: "Ingestão de alimentos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo, água, alimentos",
        sintomas: "Visão dupla, dificuldade para engolir, fraqueza muscular, paralisia",
        tratamento: "Soro antibotulínico, suporte respiratório",
        prevencao: "Conservação adequada de alimentos, cozimento adequado, não consumir alimentos enlatados estufados"
    },
    {
        nome: "Candidíase",
        outros: "Sapinho",
        agentes: "Candida albicans",
        tipoAgente: "levedura",
        descricao: "Infecção fúngica que pode afetar a pele, boca, vagina e outros órgãos.",
        periodoIncubacao: "Varia, geralmente após a quebra da barreira imunológica",
        transmissao: "Contato direto com a levedura, objetos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Flora normal do corpo humano",
        sintomas: "Vermelhidão, coceira, placas brancas na boca ou vagina",
        tratamento: "Antifúngicos",
        prevencao: "Manutenção da higiene, tratamento de doenças crônicas"
    },
    {
        nome: "Blastomicose",
        outros: "Doença de Gilchrist",
        agentes: "Blastomyces dermatitidis",
        tipoAgente: "fungo dimórfico",
        descricao: "Infecção fúngica pulmonar crônica que pode se disseminar para outros órgãos.",
        periodoIncubacao: "Semanas a meses",
        transmissao: "Inalação de esporos do fungo",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo, material em decomposição",
        sintomas: "Febre, tosse, fadiga, lesões cutâneas",
        tratamento: "Antifúngicos",
        prevencao: "Evitar áreas com alta incidência do fungo, usar máscaras em áreas contaminadas"
    },
    {
        nome: "Mucormicose",
        outros: "Zigomicose",
        agentes: "Rhizopus, Mucor, Absidia",
        tipoAgente: "fungo zigomiceto",
        descricao: "Infecção fúngica grave, geralmente oportunista, que pode afetar os seios da face, pulmões e cérebro.",
        periodoIncubacao: "Dias a semanas",
        transmissao: "Inalação de esporos do fungo, penetração cutânea",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo, material vegetal em decomposição",
        sintomas: "Febre, dor de cabeça, sintomas nasais, lesões cutâneas",
        tratamento: "Antifúngicos, cirurgia",
        prevencao: "Controle do diabetes, imunossupressão, higiene"
    },
    {
        nome: "Ancilostomíase",
        outros: "Amarelão",
        agentes: "Ancylostoma duodenale, Necator americanus",
        tipoAgente: "helminto (nematódeo)",
        descricao: "Infecção intestinal causada por nematódeos que se alimentam do sangue do hospedeiro.",
        periodoIncubacao: "4 - 8 semanas",
        transmissao: "Penetração ativa das larvas através da pele, geralmente nos pés",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo contaminado com fezes",
        sintomas: "Coceira no local de penetração, anemia, dor abdominal, diarreia",
        tratamento: "Vermífugos",
        prevencao: "Uso de calçados, saneamento básico, tratamento de água"
    },
    {
        nome: "Catapora",
        outros: "Varicela",
        agentes: "Vírus varicela-zoster (VZV)",
        tipoAgente: "vírus DNA envelopado",
        descricao: "Doença infecciosa altamente contagiosa caracterizada por erupção cutânea com vesículas pruriginosas.",
        periodoIncubacao: "10 - 21 dias",
        transmissao: "Contato direto com as lesões, gotículas respiratórias e contato com objetos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Febre, mal-estar, perda de apetite, erupção cutânea",
        complicacoes: "Infecções bacterianas secundárias, pneumonia, encefalite",
        tratamento: "Antivirais (em casos graves), cuidados para aliviar os sintomas",
        prevencao: "Vacina contra a varicela, isolamento do doente"
    },
    {
        nome: "Varíola do Macaco",
        outros: "Monkeypox",
        agentes: "Vírus da varíola do macaco",
        tipoAgente: "vírus DNA envelopado",
        descricao: "Doença infecciosa zoonótica com sintomas semelhantes à varíola, mas geralmente menos graves.",
        periodoIncubacao: "5 - 21 dias",
        transmissao: "Contato direto com lesões, fluidos corporais, gotículas respiratórias e materiais contaminados",
        definitivo: "Roedores, primatas não humanos",
        intermediario: "Humanos",
        reservatorio: "Roedores",
        sintomas: "Febre, dor de cabeça, linfadenopatia, erupção cutânea",
        complicacoes: "Pneumonia, encefalite, septicemia",
        tratamento: "Tratamento de suporte, antivirais (em alguns casos) ",
        prevencao: "Evitar contato com animais infectados, isolamento do doente, vacina contra a varíola (pode oferecer alguma proteção)"
    },
    {
        nome: "Gonorreia",
        outros: "Blenorragia",
        agentes: "Neisseria gonorrhoeae",
        tipoAgente: "diplococo gram negativo",
        descricao: "Doença sexualmente transmissível que infecta as mucosas urogenital, anal e orofaríngea.",
        periodoIncubacao: "2 - 7 dias",
        transmissao: "Contato sexual",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Uretra inflamada, corrimento uretral, dor ao urinar, dor abdominal inferior (em mulheres)",
        complicacoes: "Doença inflamatória pélvica, infertilidade, disseminação sistêmica",
        tratamento: "Antibióticos (ceftriaxona e azitromicina)",
        prevencao: "Uso de preservativos, exames regulares, tratamento de parceiros sexuais"
    },
    {
        nome: "Histoplasmose",
        outros: "Febre de Ohio",
        agentes: "Histoplasma capsulatum",
        tipoAgente: "levedura",
        descricao: "Doença infecciosa sistêmica causada pela inalação de microrganismos, com manifestações pulmonares e, em alguns casos, disseminação para outros órgãos.",
        periodoIncubacao: "3 - 17 dias",
        transmissao: "Inalação de esporos presentes em ambientes contaminados por excrementos de morcegos e aves",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Morcegos, aves",
        sintomas: "Febre, tosse, dor torácica, fadiga",
        complicacoes: "Adenoma pulmonar, mediastinite, disseminação para outros órgãos",
        diagnostico: "Cultura, histopatologia, sorologia",
        tratamento: "Antifúngicos (itraconazol, anfotericina B)",
        prevencao: "Evitar ambientes contaminados, uso de máscaras em áreas de risco"
    },
    {
        nome: "Doença de Chagas",
        outros: "Mal de Chagas",
        agentes: "Trypanosoma cruzi",
        tipoAgente: "protozoário",
        descricao: "Doença parasitária crônica que acomete o sistema nervoso autônomo, o trato gastrointestinal e o coração.",
        periodoIncubacao: "Varia, pode ser indeterminado",
        transmissao: "Picada de triatomíneos (barbeiros), transfusão sanguínea, transplante de órgãos, congenita",
        definitivo: "Humanos",
        intermediario: "Triatomíneos",
        reservatorio: "Roedores, marsupiais",
        sintomas: "Fase aguda: febre, edema, linfadenopatia; fase crônica: cardiomegalia, megaesôfago, megacolon",
        complicacoes: "Insuficiência cardíaca, dilatação de órgãos",
        diagnostico: "Exame parasitológico, xenodiagnóstico, sorologia",
        tratamento: "Benznidazol e nifurtimox (fase aguda), tratamento sintomático (fase crônica)",
        prevencao: "Controle de vetores, triagem de sangue, educação em saúde"
    },
    {
        nome: "Paracoccidioidomicose",
        outros: "Blastomicose sul-americana",
        agentes: "Paracoccidioides brasiliensis",
        tipoAgente: "levedura",
        descricao: "Micose sistêmica crônica que acomete principalmente os pulmões, mucosa oral e pele.",
        periodoIncubacao: "Varia, pode ser indeterminado",
        transmissao: "Inalação de conídios",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo",
        sintomas: "Lesões ulceradas na mucosa oral, adenopatia, febre, emagrecimento",
        complicacoes: "Disseminação para outros órgãos, insuficiência respiratória",
        diagnostico: "Exame direto, cultura, histopatologia, sorologia",
        tratamento: "Antifúngicos (itraconazol, anfotericina B)",
        prevencao: "Evitar áreas endêmicas, uso de máscaras em áreas de risco"
    },
    {
        nome: "Antraz",
        outros: "Carbúnculo",
        agentes: "Bacillus anthracis",
        tipoAgente: "bacilo gram positivo",
        descricao: "Doença infecciosa zoonótica que pode acometer a pele, o trato respiratório ou o trato gastrointestinal.",
        periodoIncubacao: "Varia de acordo com a forma de apresentação",
        transmissao: "Contato com animais infectados, esporos presentes no solo, inalação de esporos",
        definitivo: "Ruminantes, humanos",
        intermediario: "Não aplicável",
        reservatorio: "Solo contaminado com esporos",
        sintomas: "Cutânea: úlcera com crosta negra; respiratória: febre, tosse, dificuldade respiratória; gastrointestinal: náuseas, vômitos, diarreia",
        complicacoes: "Septicemia, choque, morte",
        diagnostico: "Cultura, PCR, imunofluorescência",
        tratamento: "Antibióticos(ciprofloxacina, doxiciclina), antitoxina",
        prevencao: "Vacinação de animais e pessoas em risco, medidas de biossegurança"
    },
    {
        nome: "Coqueluche",
        outros: "Tosse comprida",
        agentes: "Bordetella pertussis",
        tipoAgente: "coco gram negativo",
        descricao: "Doença infecciosa aguda das vias aéreas superiores, caracterizada por tosse paroxística intensa.",
        periodoIncubacao: "7 - 10 dias",
        transmissao: "Gotículas respiratórias",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Tosse intensa, vômitos, dificuldade para respirar",
        complicacoes: "Pneumonia, convulsões, encefalopatia",
        diagnostico: "Cultura, PCR, teste rápido",
        tratamento: "Antibióticos (eritromicina, azitromicina), tratamento sintomático",
        prevencao: "Vacina tríplice bacteriana (DTP), reforços, isolamento do doente"
    },
    {
        nome: "HPV",
        outros: "Papilomavírus Humano",
        agentes: "Diferentes tipos de HPV",
        tipoAgente: "vírus DNA não envelopado",
        descricao: "Infecção sexualmente transmissível que pode causar verrugas genitais e câncer, principalmente do colo do útero.",
        periodoIncubacao: "Semanas a meses",
        transmissao: "Contato sexual, contato pele a pele com lesões",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Verrugas genitais, lesões pré-cancerosas, câncer (colo do útero, ânus, boca, garganta)",
        complicacoes: "Câncer, verrugas recorrentes",
        diagnostico: "Colposcopia, exame de Papanicolaou, biópsia",
        tratamento: "Remoção das verrugas, imunoterapia (em alguns casos)",
        prevencao: "Vacina contra o HPV, uso de preservativo, exames ginecológicos regulares"
    },
    {
        nome: "Pneumonia Bacteriana",
        outros: "Inflamação dos pulmões",
        agentes: "Streptococcus pneumoniae, Haemophilus influenzae, Staphylococcus aureus",
        tipoAgente: "bactéria",
        descricao: "Infecção aguda dos pulmões, geralmente causada por bactérias, caracterizada por inflamação dos alvéolos pulmonares.",
        periodoIncubacao: "1 - 3 dias",
        transmissao: "Gotículas respiratórias",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Febre, tosse com catarro, dor no peito, dificuldade para respirar",
        complicacoes: "Sepse, abscesso pulmonar, insuficiência respiratória",
        tratamento: "Antibióticos",
        prevencao: "Vacinação contra o pneumococo, higiene das mãos, cobertura da boca ao tossir ou espirrar"
    },
    {
        nome: "Forúnculo",
        outros: "Bicho",
        agentes: "Staphylococcus aureus",
        tipoAgente: "bactéria",
        descricao: "Infecção aguda da raiz do pelo, caracterizada por um nódulo vermelho e doloroso.",
        periodoIncubacao: "1 - 7 dias",
        transmissao: "Contato com a pele infectada",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Nódulo vermelho e doloroso, pus",
        complicacoes: "Celulite, abscesso",
        tratamento: "Antibióticos, drenagem do abscesso",
        prevencao: "Higiene pessoal, cuidado com feridas"
    },
    {
        nome: "Síndrome de Fournier",
        outros: "Gangrena sinérgica",
        agentes: "Várias bactérias (aeróbias e anaeróbias)",
        tipoAgente: "bacteriana",
        descricao: "Infecção necrosante grave dos órgãos genitais externos, geralmente em homens.",
        periodoIncubacao: "Rápido, horas a dias",
        transmissao: "Infecção secundária a feridas, procedimentos cirúrgicos ou doenças de base",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Não aplicável",
        sintomas: "Dor intensa, inchaço, vermelhidão, febre, choque",
        complicacoes: "Sepse, morte",
        tratamento: "Cirurgia, antibióticos de amplo espectro, desbridamento",
        prevencao: "Controle do diabetes, higiene pessoal, tratamento precoce de infecções"
    },
    {
        nome: "Ascaridíase",
        outros: "Lombriga",
        agentes: "Ascaris lumbricoides",
        tipoAgente: "helminto (nematódeo)",
        descricao: "Doença parasitária intestinal causada por um verme cilíndrico",
        periodoIncubacao: "2 - 3 meses",
        transmissao: "Ingestão de ovos do parasita presentes em alimentos, água ou solo contaminados com fezes humanas",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Dor abdominal, náuseas, vômitos, diarreia, perda de peso, tosse",
        complicacoes: "Obstrução intestinal, perfuração intestinal, migração para outros órgãos",
        tratamento: "Vermífugos (mebendazol, albendazol)",
        prevencao: "Saneamento básico, higiene pessoal, lavagem de alimentos, uso de calçados"
    },
    {
        nome: "Herpes Labial",
        outros: "Febre labial",
        agentes: "Vírus Herpes Simplex tipo 1 (HSV-1)",
        tipoAgente: "vírus DNA envelopado",
        descricao: "Infecção viral que causa feridas dolorosas nos lábios e ao redor da boca",
        periodoIncubacao: "2 - 12 dias",
        transmissao: "Contato direto com as lesões, saliva, objetos contaminados",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Coceira, formigamento, pequenas bolhas que se rompem e formam feridas, febre baixa",
        complicacoes: "Disseminação para outras partes do corpo, infecções secundárias",
        tratamento: "Antivirais (aciclovir, valaciclovir), tratamento sintomático",
        prevencao: "Evitar contato com lesões ativas, higiene pessoal"
    },
    {
        nome: "Herpes Genital",
        outros: "não tem",
        agentes: "Vírus Herpes Simplex tipo 2 (HSV-2)",
        tipoAgente: "vírus DNA envelopado",
        descricao: "Infecção sexualmente transmissível que causa feridas dolorosas nos órgãos genitais",
        periodoIncubacao: "2 - 12 dias",
        transmissao: "Contato sexual",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Feridas dolorosas nos órgãos genitais, febre, linfadenopatia",
        complicacoes: "Herpes neonatal, infecções recorrentes, aumento do risco de câncer cervical",
        tratamento: "Antivirais (aciclovir, valaciclovir), tratamento sintomático",
        prevencao: "Uso de preservativo, redução do número de parceiros sexuais, diagnóstico precoce e tratamento"
    },
    {
        nome: "Erisipela",
        outros: "não tem",
        agentes: "Streptococcus pyogenes",
        tipoAgente: "estreptococo gram positivo",
        descricao: "Infecção bacteriana aguda da pele, caracterizada por vermelhidão, inchaço e dor.",
        periodoIncubacao: "2 - 10 dias",
        transmissao: "Penetração do Streptococcus pyogenes por feridas na pele",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Vermelhidão, inchaço, dor, febre, calafrios",
        complicacoes: "Celulite, linfangite, bacteremia",
        tratamento: "Antibióticos (penicilina)",
        prevencao: "Cuidado com feridas, higiene pessoal, tratamento de infecções de pele"
    },
    {
        nome: "Chicungunha",
        outros: "Chicungunya",
        agentes: "Vírus da chicungunha",
        tipoAgente: "vírus RNA envelopado",
        descricao: "Doença viral transmitida por mosquitos, caracterizada por febre alta, dores articulares intensas e erupção cutânea.",
        periodoIncubacao: "3 - 7 dias",
        transmissao: "Picada do mosquito Aedes aegypti",
        definitivo: "Humanos",
        intermediario: "Aedes aegypti",
        reservatorio: "Humanos",
        sintomas: "Febre alta, dores articulares intensas, dor de cabeça, fadiga, erupção cutânea",
        complicacoes: "Artrites crônicas, encefalite",
        tratamento: "Tratamento sintomático",
        prevencao: "Combate ao mosquito Aedes aegypti, uso de repelentes, proteção contra picadas"
    },
    {
        nome: "Herpes Zoster",
        outros: "Cobreiro",
        agentes: "Vírus Varicela-Zoster (VZV)",
        tipoAgente: "vírus DNA envelopado",
        descricao: "Doença infecciosa caracterizada por uma erupção cutânea dolorosa em um lado do corpo, geralmente seguindo o trajeto de um nervo.",
        periodoIncubacao: "10 - 21 dias",
        transmissao: "Reativação do vírus varicela-zoster (causador da catapora) em pessoas que já tiveram a doença",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Dor, coceira, erupção cutânea com vesículas, febre",
        complicacoes: "Neuralgia pós-herpética, infecções bacterianas secundárias, encefalite",
        tratamento: "Antivirais (aciclovir, valaciclovir), analgésicos, cuidados com a pele",
        prevencao: "Vacina contra o zoster, tratamento da varicela"
    },
    {
        nome: "Hanseníase",
        outros: "Lepra",
        agentes: "Mycobacterium leprae",
        tipoAgente: "bacilo gram positivo",
        descricao: "Doença crônica causada por uma bactéria que afeta a pele, os nervos, os olhos e as vias aéreas superiores.",
        periodoIncubacao: "5 a 15 anos",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Manchas na pele, perda de sensibilidade, nódulos, fraqueza muscular",
        transmissao: "Contato prolongado com secreções de pessoas doentes",
        tratamento: "Poliquimioterapia (PQT) com antibióticos",
        prevencao: "Diagnóstico precoce, tratamento dos casos, educação em saúde"
    },
    {
        nome: "Tracoma",
        outros: "Oftalmia",
        agentes: "Chlamydia trachomatis",
        tipoAgente: "bactéria",
        descricao: "Infecção bacteriana crônica dos olhos, que pode levar à cegueira.",
        periodoIncubacao: "5-7 dias",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Vermelhidão, coceira, lacrimejamento, sensação de corpo estranho no olho",
        transmissao: "Contato direto com secreções oculares de pessoas infectadas",
        tratamento: "Antibióticos",
        prevencao: "Higiene facial, acesso à água limpa, tratamento dos casos"
    },
    {
        nome: "Pitiríase versicolor",
        outros: "Tinha versicolor",
        agentes: "Leveduras do gênero Malassezia",
        tipoAgente: "levedura",
        descricao: "Infecção fúngica da pele que causa manchas descoloridas",
        periodoIncubacao: "Varia",
        definitivo: "Humanos",
        intermediario: "Não aplicável",
        reservatorio: "Humanos",
        sintomas: "Manchas brancas, rosadas ou marrons na pele, principalmente no tronco e nos braços",
        transmissao: "Contato direto com a pele de pessoas infectadas ou objetos contaminados",
        tratamento: "Antifúngicos tópicos",
        prevencao: "Manter a pele limpa e seca, evitar o uso de roupas apertadas"
    }
];